name: flutter_application_messege
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  intl: ^0.18.1
  freezed: ^2.1.0+1
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.9
  progress_indicators: ^1.0.0
  cached_network_image: ^3.3.1
  easy_localization: ^3.0.0
  dartz: ^0.10.1
  built_value: ^8.8.1
  built_collection: ^5.1.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.4




flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translation/
    - assets/images/
    - assets/icons/svg/


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/fonts/sf_pro_display/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/fonts/sf_pro_display/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/fonts/sf_pro_display/sf-pro-text-regular.ttf
          weight: 400

